---
title: "PS1 Exercise 1"
author: "Elliot"
output: word_document
---
```{r include = FALSE}
library (tidyverse)
```

```{r include = TRUE}
greenbuildings <- read.csv("greenbuildings.csv")
y = greenbuildings$Rent
summary(y)

yTotal = y*greenbuildings$size
summary(yTotal)

green = greenbuildings$green_rating

#indices of rows that are green (g) vs not green (n)
g = which(green == 1)
n = which(green == 0)

length(g)
length(n)
 
#density plots
dg = density(y[g])
plot(dg, xlab = "$/sq ft", main = "Density plot of rents for green and non-green apartments", ylim=c(0,.05), col = 'green')

dn = density(y[n])
lines(dn)

labels = c('Green', 'Non-green')
legend('topright', labels, col = c("green","black"), lty = c(1,1))

#remove low occupancy
low = which(greenbuildings$leasing_rate < 10)
high = which(greenbuildings$leasing_rate >= 10)

newdata = greenbuildings[high,]

green = newdata$green_rating

#indices of rows that are green (g) vs not green (n)
g = which(green == 1)
n = which(green == 0)

length(g)
length(n)

y = newdata$Rent

#density plots
dg = density(y[g])

plot(dg, xlab = "rent per sq ft", main = "density plot of rents for green and not green apartments", ylim=c(0,.05), col = 'green')

dn = density(y[n])
lines(dn)

labels = c('green', 'non-green')
legend('topright', labels, col = c("green","black"), lty = c(1,1))

res = cor(newdata)
View(res)

res2 = cbind(res[,5], res[,14])
colnames(res2) = c("rent", "green")
View(res2)

#try: age
age = newdata$age
rent = newdata$Rent
plot(rent ~ age, cex = 0.5)

abline(lm(rent~age), lwd = 2, col = "red")

#try class_a
class_a = newdata$age
rent = newdata$Rent
plot(rent ~ class_a, cex = 0.5)

abline(lm(rent~class_a), lwd = 2, col = "red")

#try amenities 
amenities = newdata$amenities
rent = newdata$Rent
plot(rent~amenities, cex = 0.5)

abline(lm(rent~amenities), lwd = 2, col = "red")
#amenities is a categorical variable so this plot wasn't useful maybe try finding mean/median

#try leasing rate
leasing_rate = newdata$leasing_rate
rent = newdata$Rent
plot(rent~leasing_rate, cex = 0.5)
abline(lm(rent~amenities), lwd = 2, col = "red")
#this showed a positive relationship but not the most convincing plot
```
