---
title: "Exercise 1, Problem 1"
output: github_document
---

```{r include = FALSE}
greenbuildings <- read.csv("greenbuildings.csv")
library(ggplot2)
library(tidyverse)
#################################################################################

#remove zero occupancy
NonZero = subset(greenbuildings, leasing_rate > 0)
Young = subset(NonZero, age < 20)
# oldest green buildling is 19 based on max green1
# split up into green and non green
NonGreen1 <- subset(Young, green_rating==0)
Green1 <- subset(Young, green_rating==1)


# pipes
Green_summ <- Green1 %>%
  group_by(age, green_rating==1) %>%
  summarize(leasing_rate = mean(leasing_rate)/100)

NonGreen_summ <- NonGreen1 %>%
  group_by(age, green_rating==0) %>%
  summarize(leasing_rate = mean(leasing_rate)/100)

# line charts
BAOR = ggplot() + 
  geom_line(data = Green_summ, aes(x = age, y = leasing_rate), color = "chartreuse3") +
  geom_line(data = NonGreen_summ, aes(x = age, y = leasing_rate), color = "burlywood4") + 
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  labs(title = "Building Age and Occupancy Rate",
     y = "Occupancy rate",
     x = "Age of the building (years)") + 
  theme_minimal()
```

```{r include = TRUE}
BAOR
```

```{r include = TRUE}
boxplot(Rent~green_rating, data=Young, main="Rent by Building Type", 
        xlab="Green Building Designation", ylab="Rent ($)",
        ylim=c(0, 90))
```        

```{r include = FALSE}
# median rents
median(NonGreen1$Rent)
median(Green1$Rent)
# $0.60 premium/sq ft for green buildings

# building size * premium
GreenPayoff = 250000 * 0.60
# $150k/year at max occupancy

# factor in occupancy rate for all 19 years
Green_summ$ActualPayoff <- GreenPayoff * Green_summ$leasing_rate
Green_summ$GuruPayoff <- 650000

# amount paid after 19 years
sum(Green_summ$ActualPayoff)
sum(Green_summ$GuruPayoff)

#####################################
# guru vs me
table <- matrix(c(
  sum(Green_summ$ActualPayoff),
  sum(Green_summ$GuruPayoff)
  ), ncol=1, byrow=TRUE)
colnames(table) <- c("Payoff")
rownames(table) <- c("Our analysis","Guru")
table <- as.table(table)
```
```{r include = TRUE}
table
```
